/* Generated By:JavaCC: Do not edit this line. MessageParserConstants.java */
package ca.utoronto.msrg.padres.common.message.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MessageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int EQ = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int ISPRESENT = 10;
  /** RegularExpression Id. */
  int SOPERATOR = 11;
  /** RegularExpression Id. */
  int IOPERATOR = 12;
  /** RegularExpression Id. */
  int COPERATOR = 13;
  /** RegularExpression Id. */
  int ANAME = 14;
  /** RegularExpression Id. */
  int TIMEFORMAT = 15;
  /** RegularExpression Id. */
  int AVALZEROINT = 16;
  /** RegularExpression Id. */
  int AVALSTR = 17;
  /** RegularExpression Id. */
  int AVALLONG = 18;
  /** RegularExpression Id. */
  int AVALDOUBLE = 19;
  /** RegularExpression Id. */
  int SVARIABLE = 20;
  /** RegularExpression Id. */
  int IVARIABLE = 21;
  /** RegularExpression Id. */
  int IVAR = 22;
  /** RegularExpression Id. */
  int SVAR = 23;
  /** RegularExpression Id. */
  int FVAR = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"class\"",
    "\",\"",
    "\"eq\"",
    "\";\"",
    "\":\"",
    "\"isPresent\"",
    "<SOPERATOR>",
    "<IOPERATOR>",
    "<COPERATOR>",
    "<ANAME>",
    "<TIMEFORMAT>",
    "<AVALZEROINT>",
    "<AVALSTR>",
    "<AVALLONG>",
    "<AVALDOUBLE>",
    "<SVARIABLE>",
    "<IVARIABLE>",
    "<IVAR>",
    "<SVAR>",
    "<FVAR>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
